networks:
  myNetwork:

services:

  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    container_name: zookeeper_1
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - myNetwork

  kafka:
    image: 'wurstmeister/kafka:latest'
    container_name: kafka_1
    user: root
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LOG_RETENTION_MS=10000
      - KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS=1000
    #    volumes:
    #      - ./Kafka:/bitnami/kafka
    networks:
      - myNetwork
    depends_on:
      - zookeeper